// THROWAWAY: three private-draft list layouts at #/prototype/drafts? via ?variant=A/B/C.
// In-memory only. Decide placement and deletion affordance before implementation.
import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, ChevronRight, FilePenLine, LockKeyhole, MoreHorizontal, Plus, ReceiptText, RotateCcw, Trash2, Users, LayoutGrid, Settings, Check, Image } from 'lucide-react';
import { Button, Logo } from './ui';
import Dialog from './Dialog';
import './play.css';
import './DraftListPrototype.css';

type Draft = { id: string; title: string; total: string; items: number; photo: boolean; saved: string; mode: string };
const initial: Draft[] = [
  { id: 'costco', title: 'Costco weekend shop', total: '186.42', items: 12, photo: true, saved: 'Today, 2:45 PM', mode: 'Split by items' },
  { id: 'dinner', title: 'Friday dinner', total: '74.50', items: 0, photo: false, saved: 'Yesterday, 7:20 PM', mode: 'Split by amount' },
  { id: 'untitled', title: '', total: '', items: 3, photo: true, saved: 'Sep 14, 11:08 AM', mode: 'Split by items' },
];
const titles = { A: 'Direct actions', B: 'Draft cards', C: 'Draft drawer' };
type Variant = keyof typeof titles;
type Props = { drafts: Draft[]; open: (d: Draft) => void; remove: (d: Draft) => void };
const name = (d: Draft) => d.title || 'Untitled bill';
const amount = (d: Draft) => d.total ? `CAD ${d.total}` : 'Total not entered';
function DraftHeading({ count }: { count: number }) { return <div className="dp-section-title"><div><h2>Your drafts <span>{count}</span></h2><p><LockKeyhole size={13} /> Only you can see these. They do not affect group balances.</p></div></div>; }
export function VariantA({ drafts, open, remove }: Props) { return <section className="dp-list"><DraftHeading count={drafts.length} />{drafts.map(d => <div className="dp-row" key={d.id}><span className="dp-file"><FilePenLine size={23} /></span><div className="dp-row-copy"><strong>{name(d)}</strong><small>{d.mode} · Saved {d.saved}</small></div><span className="dp-amount">{amount(d)}</span><Button variant="secondary" onClick={() => open(d)}>Continue <ArrowRight size={16} /></Button><button className="dp-trash" aria-label={`Delete ${name(d)}`} onClick={() => remove(d)}><Trash2 size={18} /></button></div>)}</section>; }
export function VariantB({ drafts, open, remove }: Props) {
  const [menu, setMenu] = useState<string | null>(null);
  return <section><DraftHeading count={drafts.length} /><div className="dp-cards">{drafts.map(d => <article className="dp-card" key={d.id}><div className="dp-card-top"><span className="dp-file">{d.photo ? <ReceiptText size={25} /> : <FilePenLine size={25} />}</span><div className="dp-more"><button className="icon-button" aria-label={`More actions for ${name(d)}`} aria-expanded={menu === d.id} onClick={() => setMenu(menu === d.id ? null : d.id)}><MoreHorizontal size={21} /></button>{menu === d.id && <div className="dp-menu"><button onClick={() => { setMenu(null); remove(d); }}><Trash2 size={16} /> Delete draft</button></div>}</div></div><h3>{name(d)}</h3><p>{d.photo ? `${d.items} items · Receipt attached` : d.mode}</p><strong className="dp-card-total">{amount(d)}</strong><small>Saved {d.saved}</small><Button variant="secondary" onClick={() => open(d)}>Continue draft <ArrowRight size={16} /></Button></article>)}</div></section>;
}
export function VariantC({ drafts, open, manage }: Props & { manage: () => void }) { return <section className="dp-summary"><span className="dp-file"><FilePenLine size={26} /></span><div><h2>{drafts.length} private {drafts.length === 1 ? 'draft' : 'drafts'}</h2><p>{drafts.length ? `Pick up where you left off with ${name(drafts[0])}.` : 'Save a new bill to finish it later.'}</p></div><div className="dp-summary-actions">{drafts[0] && <Button variant="secondary" onClick={() => open(drafts[0])}>Continue latest</Button>}<button className="dp-text" onClick={manage}>Manage drafts <ChevronRight size={16} /></button></div></section>; }
export default function DraftListPrototype() {
  const [variant, setVariant] = useState<Variant>(() => { const v = new URLSearchParams(location.search).get('variant'); return v === 'B' || v === 'C' ? v : 'A'; });
  const [drafts, setDrafts] = useState(initial);
  const [editing, setEditing] = useState<Draft | null>(null);
  const [baseline, setBaseline] = useState<Draft | null>(null);
  const [discard, setDiscard] = useState(false);
  const [deleting, setDeleting] = useState<Draft | null>(null);
  const [drawer, setDrawer] = useState(false);
  const [notice, setNotice] = useState('');
  const [inspect, setInspect] = useState(false);
  const dirty = JSON.stringify(editing) !== JSON.stringify(baseline);
  function switchTo(v: Variant) { setVariant(v); const url = new URL(location.href); url.searchParams.set('variant', v); history.replaceState(null, '', url); console.info('Draft prototype', { variant: v, drafts }); }
  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (editing || deleting || drawer || (e.target instanceof HTMLElement && e.target.closest('input,textarea,select,[contenteditable]'))) return;
      if (e.key !== 'ArrowLeft' && e.key !== 'ArrowRight') return;
      e.preventDefault(); const keys: Variant[] = ['A', 'B', 'C']; switchTo(keys[(keys.indexOf(variant) + (e.key === 'ArrowRight' ? 1 : 2)) % 3]);
    }
    window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey);
  });
  function open(d: Draft) { setBaseline({ ...d }); setEditing({ ...d }); setDrawer(false); setNotice(''); }
  function closeEditor() { if (dirty) setDiscard(true); else { setEditing(null); setBaseline(null); } }
  function save() { if (!editing) return; const next = { ...editing, saved: 'Just now' }; setDrafts(old => old.some(d => d.id === next.id) ? old.map(d => d.id === next.id ? next : d) : [next, ...old]); setEditing(null); setBaseline(null); setNotice('Draft saved. Only you can see it.'); }
  function remove(d: Draft) { setDeleting(d); }
  const props = { drafts, open, remove };
  return <div className="play dp"><div className="app-shell"><aside className="sidebar"><Logo /><div className="workspace-label">YOUR LITTLE CORNER</div><nav className="main-nav"><button onClick={() => setNotice('This prototype focuses on drafts in your group.')}><LayoutGrid size={19} />Overview</button><button className="active" onClick={() => setNotice('You are viewing abibi.')}><Users size={19} />My groups</button><button onClick={() => setNotice('Account settings are outside this prototype.')}><Settings size={19} />Account</button></nav><div className="dp-profile"><span>SW</span><div><strong>Simian Wang</strong><small>Personal account</small></div></div></aside><main className="dp-main"><div className="dp-breadcrumb">My groups <ChevronRight size={14} /> abibi</div><header className="dp-header"><div className="dp-group-icon">a</div><div><h1>abibi</h1><p>3 members · CAD</p></div><Button onClick={() => open({ id: `new-${Date.now()}`, title: '', total: '', items: 0, photo: false, saved: '', mode: 'Split by amount' })}><Plus size={18} />New bill</Button></header><div className="dp-tabs"><span>Overview</span><span className="selected">Bills</span><span>Repayments</span></div><div className="dp-balance"><div><small>Your group balance</small><strong>You are owed <span>CAD 42.18</span></strong></div><p>From completed bills and confirmed repayments</p></div>{notice && <div role="status" className="dp-notice"><Check size={16} />{notice}</div>}{variant === 'A' ? <VariantA {...props} /> : variant === 'B' ? <VariantB {...props} /> : <VariantC {...props} manage={() => setDrawer(true)} />}{!drafts.length && variant !== 'C' && <div className="dp-empty"><FilePenLine size={28} /><h3>No drafts to finish</h3><p>Choose Save draft & close while creating a bill to keep it here.</p></div>}<section className="dp-bills"><div className="dp-section-title"><h2>Group bills <span>2</span></h2><small>Visible to everyone in abibi</small></div>{[{ title: 'Sunday groceries', meta: 'Sep 13 · Simian Wang · 3 participants', cost: '128.64' }, { title: 'Dinner at Sugo', meta: 'Sep 11 · Jamie Chen · 3 participants', cost: '96.00' }].map(b => <div className="dp-row" key={b.title}><span className="dp-file neutral"><ReceiptText size={22} /></span><div className="dp-row-copy"><strong>{b.title}</strong><small>{b.meta}</small></div><span className="dp-complete"><Check size={12} />Complete</span><strong>CAD {b.cost}</strong></div>)}</section></main></div>
  {drawer && <Dialog title="Your drafts" kicker="ONLY VISIBLE TO YOU" className="dp-drawer" close={() => setDrawer(false)}><p className="dp-muted">Continue a bill or clear out drafts you no longer need.</p><div>{drafts.length ? drafts.map(d => <article className="dp-drawer-row" key={d.id}><div><h3>{name(d)}</h3><small>Saved {d.saved}</small></div><p>{amount(d)} · {d.photo ? `${d.items} items` : d.mode}</p><div className="dp-drawer-actions"><Button variant="secondary" onClick={() => open(d)}>Continue <ArrowRight size={16} /></Button><button className="dp-text danger" onClick={() => remove(d)}><Trash2 size={16} />Delete</button></div></article>) : <p>No drafts to finish.</p>}</div></Dialog>}
  {editing && <Dialog title={drafts.some(d => d.id === editing.id) ? 'Continue your draft' : 'New bill'} kicker="abibi" close={closeEditor} className="dp-editor"><div className="dp-edit-state"><span><LockKeyhole size={14} />Private draft</span><span>{dirty ? 'Unsaved changes' : editing.saved ? `Saved ${editing.saved}` : 'Not saved'}</span></div><label>Bill title<input autoFocus value={editing.title} onChange={e => setEditing({ ...editing, title: e.target.value })} placeholder="Give this purchase a name" /></label><label>Actual paid total · CAD<input inputMode="decimal" value={editing.total} onChange={e => setEditing({ ...editing, total: e.target.value })} placeholder="0.00" /></label><div className="dp-photo"><Image size={25} /><div><strong>{editing.photo ? 'Receipt attached' : 'No receipt attached'}</strong><p>{editing.items} items · {editing.mode}</p></div></div><p className="dp-muted">Your changes stay private until you initiate the bill.</p><div className="dp-editor-footer"><Button onClick={save}>Save draft & close</Button>{drafts.some(d => d.id === editing.id) && <button className="dp-text danger" onClick={() => remove(editing)}><Trash2 size={16} />Delete draft</button>}</div><small className="dp-demo-note">Prototype: edit the title or total to try saving and discarding changes.</small></Dialog>}
  {discard && <Dialog title="Discard unsaved changes?" kicker="BEFORE YOU CLOSE" className="dp-confirm" close={() => setDiscard(false)}><p>{baseline && drafts.some(d => d.id === baseline.id) ? 'Your last saved draft will stay as it was. Changes made since opening it will be lost.' : 'This bill has not been saved. Its details will be discarded.'}</p><div className="dp-confirm-actions"><Button variant="secondary" onClick={() => setDiscard(false)}>Keep editing</Button><button className="dp-danger-button" onClick={() => { setDiscard(false); setEditing(null); setBaseline(null); setNotice('Unsaved changes discarded.'); }}>Discard changes</button></div></Dialog>}
  {deleting && <Dialog title="Delete this draft?" kicker="PRIVATE DRAFT" className="dp-confirm" close={() => setDeleting(null)}><div className="dp-delete-preview"><FilePenLine size={24} /><div><strong>{name(deleting)}</strong><small>{amount(deleting)}</small></div></div><p>This deletes the draft{deleting.photo ? ' and its receipt photo' : ''}. Your group bills and balances will not change. This cannot be undone.</p><div className="dp-confirm-actions"><Button variant="secondary" onClick={() => setDeleting(null)}>Keep draft</Button><button className="dp-danger-button" onClick={() => { setDrafts(ds => ds.filter(d => d.id !== deleting.id)); if (editing?.id === deleting.id) { setEditing(null); setBaseline(null); } setNotice(`${name(deleting)} deleted.`); setDeleting(null); }}>Delete draft</button></div></Dialog>}
  {import.meta.env.DEV && <div className="dp-prototype-controls">{inspect && <pre>{JSON.stringify({ variant, savedDrafts: drafts, editing, dirty }, null, 2)}</pre>}<div className="dp-switcher"><span className="dp-proto-label">PROTOTYPE</span><button aria-label="Previous variant" onClick={() => switchTo(variant === 'A' ? 'C' : variant === 'B' ? 'A' : 'B')}><ArrowLeft size={16} /></button><strong>{variant} · {titles[variant]}</strong><button aria-label="Next variant" onClick={() => switchTo(variant === 'A' ? 'B' : variant === 'B' ? 'C' : 'A')}><ArrowRight size={16} /></button><button aria-label="Reset sample drafts" title="Reset sample drafts" onClick={() => { setDrafts(initial); setNotice(''); }}><RotateCcw size={16} /></button><button onClick={() => setInspect(!inspect)}>State</button></div></div>}
  </div>;
}
